// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/costaconrado/services-csm/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// ProposalRepo is an autogenerated mock type for the ProposalRepo type
type ProposalRepo struct {
	mock.Mock
}

// GetHistory provides a mock function with given fields: _a0
func (_m *ProposalRepo) GetHistory(_a0 context.Context) ([]entity.Proposal, error) {
	ret := _m.Called(_a0)

	var r0 []entity.Proposal
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Proposal); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Proposal)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0, _a1
func (_m *ProposalRepo) Store(_a0 context.Context, _a1 entity.Proposal) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Proposal) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewProposalRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewProposalRepo creates a new instance of ProposalRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProposalRepo(t mockConstructorTestingTNewProposalRepo) *ProposalRepo {
	mock := &ProposalRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
