// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/costaconrado/services-csm/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// Proposal is an autogenerated mock type for the Proposal type
type Proposal struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *Proposal) Create(_a0 context.Context, _a1 entity.Proposal) (entity.Proposal, error) {
	ret := _m.Called(_a0, _a1)

	var r0 entity.Proposal
	if rf, ok := ret.Get(0).(func(context.Context, entity.Proposal) entity.Proposal); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(entity.Proposal)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.Proposal) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// History provides a mock function with given fields: _a0
func (_m *Proposal) History(_a0 context.Context) ([]entity.Proposal, error) {
	ret := _m.Called(_a0)

	var r0 []entity.Proposal
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Proposal); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Proposal)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Lock provides a mock function with given fields: _a0, _a1
func (_m *Proposal) Lock(_a0 context.Context, _a1 entity.Proposal) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Proposal) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewProposal interface {
	mock.TestingT
	Cleanup(func())
}

// NewProposal creates a new instance of Proposal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProposal(t mockConstructorTestingTNewProposal) *Proposal {
	mock := &Proposal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
