// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/costaconrado/services-csm/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// TranslationRepo is an autogenerated mock type for the TranslationRepo type
type TranslationRepo struct {
	mock.Mock
}

// GetHistory provides a mock function with given fields: _a0
func (_m *TranslationRepo) GetHistory(_a0 context.Context) ([]entity.Translation, error) {
	ret := _m.Called(_a0)

	var r0 []entity.Translation
	if rf, ok := ret.Get(0).(func(context.Context) []entity.Translation); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Translation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0, _a1
func (_m *TranslationRepo) Store(_a0 context.Context, _a1 entity.Translation) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Translation) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTranslationRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewTranslationRepo creates a new instance of TranslationRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTranslationRepo(t mockConstructorTestingTNewTranslationRepo) *TranslationRepo {
	mock := &TranslationRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
