basePath: /v1
definitions:
  entity.Customer:
    properties:
      id:
        type: integer
      name:
        example: Example Co.
        type: string
      segment:
        example: Enterprise
        type: string
      vertical:
        example: Banking and Securities
        type: string
    type: object
  entity.CustomerContact:
    properties:
      customer:
        $ref: '#/definitions/entity.Customer'
      email:
        example: john.doe@example.com
        type: string
      id:
        type: integer
      name:
        example: John Doe
        type: string
      phone:
        example: +55 (31) 9999 9999
        type: string
    type: object
  entity.Offering:
    properties:
      addons:
        items:
          $ref: '#/definitions/entity.Offering'
        type: array
      id:
        type: integer
      name:
        example: Kubernetes Adminstration Training
        type: string
      quantity:
        example: 12
        type: integer
      sku:
        example: KUB101
        type: string
      unitValue:
        example: 4100.5
        type: number
    type: object
  entity.Proposal:
    properties:
      createdAt:
        example: "2022-09-15T21:54:42.123Z"
        type: string
      customerContact:
        $ref: '#/definitions/entity.CustomerContact'
      id:
        type: integer
      offerings:
        items:
          $ref: '#/definitions/entity.Offering'
        type: array
      stage:
        example: 0
        type: integer
    type: object
  v1.response:
    properties:
      error:
        example: message
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Using a translation service as an example
  title: Go Clean Template API
  version: "1.0"
paths:
  /proposal/list:
    get:
      description: Get a list of proposals
      operationId: list-proposal
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Proposal'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
      summary: Proposal
      tags:
      - proposal
swagger: "2.0"
